# Generated by Django 2.2 on 2019-05-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
